### ISSUE TITLE
How much concurrency support?

### ISSUE THREAD

**Issue by rfyiamcool** [justinfx/pyRpc#1]
How much concurrency support?

When you use block modules, then rpc server meet block?

**Comment by justinfx** [comment]
Hi

The `PyRpc` server starts in a thread. It has an option for how many worker threads should also be started (default 1). Worker thread handle requests. So when an RPC request comes into the server, it gives it to a worker. The worker does whatever it needs to do. If that work blocks, then the worker is blocked.  But the server continues to handle requests with other available workers. 

Does that answer your question?
